config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'

  # Signup Route
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  #Login Routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #Message Route
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence:true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum:3, maximum: 15 }, uniqueness: { case_sensitive: false }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user, only: [:index]

  def index
    @message = Message.new
    @messages = Message.custom_display
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = Message.create(body: message_params[:body], user: current_user)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", message_partial: render_message(message)  
    end
  end

  private 
  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id  
      flash[:notice] = "Logged in successfully."
      redirect_to root_path
    else
      flash.now[:alert] = "Something went wrong, try again!"  
      render 'new'
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to CONNECTR #{@user.username}, you have successfully signed up!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_style_type(type)
    if type == 'notice'
      return 'success' 
    elsif type == 'alert'
      return 'error'
    end
  end
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
Say Something...
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages%>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: "ui reply form", role: "form", id: "message_form" }, url: message_path, remote: true) do |f|%>
          <div class="field">
            <div class="ui fluid input">
              <%= f.text_field :body, placeholder: "Enter a message..."%>
              <%= f.button 'Send'.html_safe, class: "ui orange icon button" %>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <%@users.each do |user|%>
            <a class="item"><%= user.username %></a>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="ui <%= alert_style_type(name)  %> floating message">
    <%= msg %>
    <i class="close icon"></i>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%if logged_in?%>
      <%= link_to "Chatroom", root_path, class: "active item"%>
    <%end%>
    <div class="right menu">
      <div class="ui dropdown item">
        <%= logged_in? ? current_user.username : "Account" %> <i class="dropdown icon"></i>
        <div class="menu">
          <%if logged_in? %>
            <%= link_to "Log out", logout_path, class: "item", method: :delete %>
          <% else %>
            <%= link_to "Log in", login_path, class: "item"%>
          <%end%>
        </div>
      </div>
      <div class="item">
        <% if !logged_in? %>
         <%= link_to "Sign Up", signup_path, class: "ui primary button"%>
         <%end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connectr</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
        <%= render 'layouts/messages' %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body%>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui error floating message">
    <i class="close icon"></i>
    <div class="header">The following errors prevented the <%= obj.class.name.downcase %> from being saved</div>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
  
<%= render 'shared/errors', obj: @user%>
<h2 class="ui center aligned icon header">
  New Account
</h2>

<div class="ui centered raised card signup-form-card">
  <div class="content">
    <%= form_with(model:@user, local:true, class: "ui form") do |f|%>
      <div class="field">
        <label><%= f.label :username %></label>
        <%= f.text_field :username, placeholder: "Username"%>
      </div>
      <div class="field">
        <label><%= f.label :password%></label>
          <%= f.password_field :password, placeholder: "Password"%>
      </div>
      <div class="field">
        <label><%= f.label :password_confirmation %></label>
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password"%>
      </div>
      <%= f.submit "Sign Up", class: "ui orange button" %>
     <%end%>
  </div>
</div>